// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "63a0e842-783f-49e0-9a22-965cf88946a7";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLineMessageChange();
void onIOTLEDChange();

String line_message;
float temp_Dashboard;
int light_Dashboard;
bool iOT_LED;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(line_message, READWRITE, ON_CHANGE, onLineMessageChange);
  ArduinoCloud.addProperty(temp_Dashboard, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(light_Dashboard, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(iOT_LED, READWRITE, ON_CHANGE, onIOTLEDChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
